// The content pipeline: where the campaign comes from, and why nothing ships unmeasured.
//
//   node tools/bake.mjs              # writes js/data/lots.js
//   PER_BAND=8 node tools/bake.mjs   # bigger campaign
//
// Every row that lands in the file has passed, in this order:
//   1. js/core/make.js built the board as the union of a random packing, so it is solvable
//      by construction rather than by hope;
//   2. the same module proved with dancing links that the packing is the *only* one
//      (countSolutions(spec, 2) === 1) — the "后验唯一" half of the generator;
//   3. the reasoning solver measured 推理深度 and the level fell inside its band's window;
//   4. this file then re-reads the *serialised* row (mask string, tuple solution) and
//      re-proves 解数 == 1 and 推理深度 == the printed number on the deserialised spec.
// Step 4 is the one that matters: it is what makes "the shipped numbers were verified" a
// sentence about the shipped bytes, not about some bytes that once existed. test/library.test.mjs
// runs the identical re-proof, so a hand-edit to js/data/lots.js fails CI.
//
// The output is deterministic: the same seeds in, byte-identical file out (no timestamps),
// which is what lets a test assert that re-baking is a no-op.

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { BANDS, makeLevel } from '../js/core/make.js';
import { maskString, normaliseSpec, parseMask, validateLevel, samePlacements } from '../js/core/board.js';
import { countSolutions } from '../js/core/dlx.js';
import { logicSolve } from '../js/core/logic.js';
import { CELLS } from '../js/core/pieces.js';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const PER_BAND = Number(process.env.PER_BAND || 6);
const SEED_NS = process.env.SEED_NS || 'pentapack-v1';
const MAX_ATTEMPTS = Number(process.env.MAX_ATTEMPTS || 600);

// Two lots are the same puzzle when the board shape *and* the piece multiset match. A run of
// the same band on nearby seeds likes to rediscover the same lump, and a campaign of
// look-alikes is not 30 levels, it is 3 levels wearing 30 costumes.
function signature(spec) {
  return `${spec.pieces.slice().sort().join('')}@${maskString(spec.mask)}`;
}

const t0 = Date.now();
const rows = [];
const seen = new Set();
const report = [];

for (const band of BANDS) {
  const picked = [];
  let n = 0;
  let attempts = 0;
  while (picked.length < PER_BAND && n < PER_BAND * 60) {
    n++;
    const seed = `${SEED_NS}:${band.key}:${n}`;
    const made = makeLevel({ seed, band, maxAttempts: MAX_ATTEMPTS });
    attempts += made.stats.attempts;
    if (!made.ok) continue;
    const sig = signature(made.spec);
    if (seen.has(sig)) continue;
    // --- step 4: re-prove from the serialised form, not from the in-memory one ---
    const row = {
      id: `${band.key}-${String(picked.length + 1).padStart(2, '0')}`,
      band: band.key,
      k: made.k,
      depth: made.depth,
      w: made.spec.w,
      h: made.spec.h,
      mask: maskString(made.spec.mask),
      pieces: made.spec.pieces.join(''),
      solution: made.solution.map((p) => [p.piece, p.variant, p.x, p.y]),
    };
    const spec = normaliseSpec({
      w: row.w, h: row.h, mask: parseMask(row.mask, row.w, row.h), pieces: row.pieces,
    });
    const err = validateLevel(spec);
    if (err) throw new Error(`${row.id}: invalid after serialisation — ${err}`);
    const count = countSolutions(spec, 2);
    if (count !== 1) throw new Error(`${row.id}: not unique after serialisation (count=${count})`);
    const logic = logicSolve(spec);
    if (!logic.solved || logic.truncated) throw new Error(`${row.id}: reasoning solver could not finish it`);
    if (logic.depth !== row.depth) {
      throw new Error(`${row.id}: depth moved ${row.depth} -> ${logic.depth}; the file would lie`);
    }
    const bakedPlacements = row.solution.map(([piece, variant, x, y]) => ({ piece, variant, x, y }));
    if (!samePlacements(bakedPlacements, logic.placements)) {
      throw new Error(`${row.id}: the shipped solution is not the one the logic solver finds`);
    }
    seen.add(sig);
    picked.push(row);
    rows.push(row);
  }
  report.push({
    band: band.key,
    want: PER_BAND,
    got: picked.length,
    seeds: n,
    attempts,
    perLot: picked.length ? (attempts / picked.length).toFixed(2) : '-',
    depths: picked.map((r) => r.depth).join(','),
    ks: picked.map((r) => r.k).join(','),
  });
  if (picked.length < PER_BAND) {
    throw new Error(`band ${band.key} only produced ${picked.length}/${PER_BAND} distinct levels — fix the generator, do not ship a short campaign`);
  }
}

const ms = Date.now() - t0;
const cells = rows.reduce((a, r) => a + r.k * CELLS, 0);

const header = `// GENERATED by tools/bake.mjs — do not edit by hand.
// Re-run with \`npm run bake\` (or PER_BAND=8 node tools/bake.mjs). The pipeline re-proves
// every row below from its serialised form: 解数 == 1 by dancing links, 推理深度 == the number
// printed here, and the shipped solution equal to the one the reasoning solver finds. See
// tools/bake.mjs for the four gates and test/library.test.mjs for the same proof in CI.

// Band ladder: each band pins a piece count and a window on the reasoning-depth measurement
// (js/core/logic.js). Depth belongs to the rule pair, not to the puzzle; if the rules change,
// re-bake, because every number below is a statement about those rules.
export const META = ${JSON.stringify({ version: 1, generator: SEED_NS, perBand: PER_BAND, bands: BANDS.length, lots: rows.length, cells }, null, 2)};

export const LOTS = [\n${rows.map((r) => '  ' + JSON.stringify(r)).join(',\n')}\n];\n`;

const outDir = join(root, 'js', 'data');
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, 'lots.js'), header);

process.stderr.write(`baked ${rows.length} lots (${cells} board cells) in ${ms}ms\n`);
for (const r of report) {
  process.stderr.write(`  ${r.band}: ${r.got} lots, ${r.seeds} seeds, ${r.attempts} packings, ${r.perLot} per lot | depths ${r.depths} | k ${r.ks}\n`);
}
const flat = rows.map((r) => r.depth);
process.stderr.write(`  depth: min ${Math.min(...flat)} med ${flat.sort((a, b) => a - b)[Math.floor(flat.length / 2)]} max ${Math.max(...flat)}\n`);
process.stderr.write(`  wrote js/data/lots.js\n`);
